### PR TITLE
Track Healing Done

### PR DESCRIPTION
**Pull request by geojak**
works and all features like announce, clear data, tooltip are supported fully (also /sdps debug but it will show everything as 100% overheal) . tracks effectie and total healing combined in one view

t2o small problems left:
1. absorbs are not tracked, sad priest
2. i had to use MikCEH.GetUnitIDFromName(target); to calc overhealing, therefore MSBT was added as dependecy until this is changed

### CODE REVIEW

**Comment by geojak** [comment]
WoWScrnShot_071422_132312

**Comment by shagu** [comment]
Regarding the dependency: To obtain the UnitID by name, you can iterate through validUnits and validPets until the UnitName() of the validUnit equals the name you have, and then return the unit. Take it a look at parser.ScanName for that, I think that should help: https://github.com/shagu/ShaguDPS/blob/master/parser.lua#L26

**Comment by geojak** [comment]
Hey thx for the feedback, I know it's quite hacky still. I am not that good at this stuff.

The think with the backgroijd removal I honestly forgot about. I did that for myself and didnt remember that it's not the normal behaviour
I will work on removing the dependency thx got the tip. There seems to be a bug anyway with that code and the overheal not displayed consistently.

I was expecting this not merge rdy, that you for the review

**Comment by geojak** [comment]
I will try to Adress all the points expect tbc. That I just won't touch, I have no way to test it anyway

**Comment by geojak** [comment]
hello shagu, i have added a few more commits which hopefully adress

1.
3.
5.
6.

maybe its better now. if you got any wishes or remakrs towards 1. 3. 5. 6. i would be very happy if to improve it further.

to the remaning points:
8. i still want to adress 8. when i get to it with your hint you gave me before 
4. not quite sure how to do 4., at a first glance it thought its better to keep the parsere separate which allows us to register different events to them. this shoud allow us to implement in the future optinla unregisters of uneeded stuff, like healing on a warrior to safe performance. so honestly not the biggest fan of merging the parser, but i could rename them to damage_parser and heal_parser?
7. i acutally like the toggleing with shift alot, its rly space efficient and fast to toggle. a dropdown menu would be less convenient to me. probably comes down to personal preference
2. i dont have acces to TBC and dont rly want to find a tbc private server just to extend the addon on a version of wow i wont play

**Comment by shagu** [comment]
Closing this PR, as Effective Healing (and HPS) is now included for Vanilla and TBC, mainly by these two commits:
https://github.com/shagu/ShaguDPS/commit/f7c7b08f351256d0a362c49bc539a20a843d9861
https://github.com/shagu/ShaguDPS/commit/257a1f12b96450f3556863e201176867b536c622

**Comment by geojak** [comment]
I checked your implementation, gj much cleaner than mine.

One thing I liked in mine better, it would both calculate effective healing  and total healing and plot both in one viewfl

So first the effective healing, also sort after that, and then in grey a bigger bar that is the total healing.

Having both in one view gives more info, like you cns see from that overheal, who blasted alot of total heal on tank for example, who is very effective with heals, who actually did most effective heal.

I think I would be a good addition.

**Comment by shagu** [comment]
Yes, that is indeed something i'd love to have and is what I will be working next.
I didn't yet checked how you exactly did it in your PR and don't know if that's still a way (since I dropped the view_xyz tables).
I'll figure out how it could be done, and how it could be implemented in a clean and sane way the next days.

Thanks for your work and for pushing the topic forward! :+1:

**Comment by geojak** [comment]
Honestly the combined view was the most work I had to put into my version.

I had to change the heal-table values to be 2 dimensional, so heal and effective heal and the change all code pieces to depending on view work with that now table of table

**Comment by shagu** [comment]
I have it on my local branch running. But it still requires cleanup and testing. I'm also unhappy with the display. It feels like it just takes too much space to write both the overheal and effective heal in the same line, especially with large heal numbers. But I don't know yet how to present it better.

**Comment by shagu** [comment]
I have now pushed my local branch to master. Please let me know if anything is missing from your PR. Thanks!

**Comment by geojak** [comment]
image

HI shagu, so here is my feedback.

as you see in the screenshot, the heal view is a bit crowded with numbers if you ask me

i wiould suggest removing the HPS and for the damage view the DPS numbers in brackets, the same i would do for heal and damage views (remvoing the DPS and HPS numbers in brackets). THese numbers are just a bit much, and if you want to see them you can always just toogle to their own separate views that also exist already. So in my opinion it is not worth it to flood the user with these aswell.

secondly to the heal view overheal number, i find a bit weird that the +overheal comes before the actuall heal.
i mean logically its effective heal + overheal = total heal
normally you would be more interested in effective heal than overheal, so i would put that number first before the oveheal.

lastly i noticed you didnt include the /dps border i included to turn borderless mode on and off. but we talked about this before and its was not rly part of the heal pulll request anyway.

i like it borderless better thought, maybe others would too

p.s. the "you" bug i had to handle doesnt affect your implementation because you wisely didnt fill the target in the parser which means the default preset player will be used. Nice

**Comment by geojak** [comment]
it appeast to me healing current is bugged.

damage works for overheal and current per fight, but healing no, it is always identical and overall

**Comment by shagu** [comment]
> as you see in the screenshot, the heal view is a bit crowded with numbers if you ask me. if you acutally heal a bit, the numbers overlap with my name even and i barley can see the bars below anymore

Yes, you are right. I'll remove those additional numbers from the other view again

> secondly to the heal view overheal number, i find a bit weird that the +overheal comes before the actuall heal.
i mean logically its effective heal + overheal = total heal
normally you would be more interested in effective heal than overheal, so i would put that number first before the oveheal.

I made it like this for a simple reason: This way the actual values of the view (those that also are the %) are vertically aligned to each other. You can always find the "normal" number on the right side, and the overheal is therefore highlighted to also see it better. If i'd put it the other way around, i personally found it chaotic looking. As it is now, only the additional value (the overheal) is placed off grid.

> lastly i noticed you didnt include the /dps border i included to turn borderless mode on and off. but we talked about this before and its was not rly part of the heal pulll request anyway.

Ah, yes. Did you only remove the border/background from the window, or also the title background?

> it appeast to me healing current is bugged.
damage works for overheal and current per fight, but healing no, it is always identical and overall

I'll have a look tomorrow :)
Thanks for your feedback! :+1:

**Comment by geojak** [comment]
i only removed the border and backdrop at the bottom not at the menu part with this command option code

elseif strlower(cmd) == "borders" then
    config.borders = config.borders == 1 and 0 or 1
    ShaguDPS_Config = config
	if config.borders == 0 then
		window.border:Hide()
		window:SetBackdrop(nil)
	else
		window.border:Show()
		window:SetBackdrop({
		  bgFile = "Interface\\Tooltips\\UI-Tooltip-Background",
		  tile = true, tileSize = 16, edgeSize = 16,
		  insets = { left = 3, right = 3, top = 3, bottom = 3 }
		})
		window:SetBackdropColor(.5,.5,.5,.5)
	end
    p("|cffffcc00Shagu|cffffffffDPS:|cffffddcc Borders: " .. config.borders)
  end

in the second comment at the very top of this you can see a screenshot how it would look like

**Comment by geojak** [comment]
ah i forgot some code for the border thing to work on login

-- Load settings on Login
settings:RegisterEvent("PLAYER_ENTERING_WORLD")
settings:SetScript("OnEvent", function()
  if ShaguDPS_Config then
    for k, v in pairs(ShaguDPS_Config) do
      config[k] = v
    end
  end

  ShaguDPS_Config = config
  if config.borders == 0 then
	window.border:Hide()
	window:SetBackdrop(nil)
  else
	window.border:Show()
	window:SetBackdrop({
	  bgFile = "Interface\\Tooltips\\UI-Tooltip-Background",
	  tile = true, tileSize = 16, edgeSize = 16,
	  insets = { left = 3, right = 3, top = 3, bottom = 3 }
	})
	window:SetBackdropColor(.5,.5,.5,.5)
	end
  window.Refresh(true)
end)

**Pull request closed without merging**
